### ISSUE TITLE
no fractal chain

### ISSUE THREAD

**Issue by lllanlll** [fractal-bitcoin/ord#4]
when i run 
ord --chain=fractal-mainnet server

error: invalid value 'fractal-mainnet' for '--chain <CHAIN_ARGUMENT>'
  [possible values: mainnet, testnet, signet, regtest]

**Comment by lllanlll** [comment]
and the doc has error command

error: ord server --chain=fractal-mainnet

ord --chain=fractal-mainnet server

**Comment by crackeryo** [comment]
did you pull from the fractal ord repo?

I think they forgot to update the readme file

**Comment by lllanlll** [comment]
I am in the `fractal-bitcoin/ord` repository. Is this the correct repository? I tried two branches, but neither of them worked.

I used the command:
```cargo build --release```
to build the `ord` file.

Then, I ran:
```ord --chain=fractal-mainnet server```

However, it still reports errors.

**Comment by slient-coder** [comment]
Please make sure you are on the fractal branch.

**Comment by lllanlll** [comment]
Yes, I can confirm that.
<img width="326" alt="image" src="https://github.com/user-attachments/assets/695873da-0f7d-4609-b0c3-22cac903a22c">
<img width="455" alt="image" src="https://github.com/user-attachments/assets/f052feeb-840b-48bd-9389-a67b80d4dddf">
but
<img width="472" alt="image" src="https://github.com/user-attachments/assets/b4931076-7b4b-4439-8330-587e3f5e137b">
